name: ðŸ§ª
# https://stackoverflow.com/questions/71155641/github-actions-how-to-view-inputs-for-workflow-dispatch
run-name: '${{ inputs.pnames }}: ${{ inputs.repository }}#${{ inputs.ref }}'
# run-name: '[Experimental] plemoljp-nf: kachick/nixpkgs#aa32ada9e1344d0a3abb64ffc806f8b07732fe4c' # Enable only when developing
on:
  # pull_request: # Enable only when developing
  workflow_dispatch:
    inputs:
      # Accept multiple packages for use-case of crystal. e.g crystal_1_11 and crystal_1_16
      pnames:
        description: 'Package names to build'
        required: true
        type: string
        default: |
          [ "gnugrep" ]
      repository:
        description: 'GitHub repository'
        # Cannot use ${{ github.repository_owner }} here.
        default: 'pineapplehunter/nixpkgs'
        required: true
        type: string
      ref:
        description: 'git ref'
        default: 'nixpkgs-unstable'
        required: true
        type: string
      runners:
        description: 'Runners'
        required: true
        # It does not allow list and multiline string.
        #   - https://github.com/orgs/community/discussions/12882
        #   - https://github.com/actions/toolkit/issues/184
        type: string
        default: |
          [ "ubuntu-24.04", "ubuntu-24.04-arm", "macos-26", "macos-15-intel" ]
      sandbox:
        description: 'Sandbox mode'
        type: boolean # `inputs.sandbox` will be boolean, but `github.event.inputs.sandbox` will be string. This is hacky, but useful for using the value in shellscripts
        default: true
      force-rebuild:
        description: Force rebuild
        type: boolean
        default: false

# env: # Enable only when developing
#   pname: 'plemoljp-nf'
#   repository: 'kachick/nixpkgs'
#   ref: 'aa32ada9e1344d0a3abb64ffc806f8b07732fe4c'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: '${{ fromJson(inputs.runners) }}'
        pname: '${{ fromJson(inputs.pnames) }}'
    runs-on: ${{ matrix.runner }}
    # timeout-minutes: 180 # Any limitations might not fit for this repository. So temporary disabling
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: '${{ inputs.repository }}'
          ref: '${{ inputs.ref }}'

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          extra_nix_config: |
            sandbox = ${{ github.event.inputs.sandbox }}

      - name: Outputs nix version and the config
        run: |
          nix --version
          nix config show

      - name: Ensure sandbox mode
        run: |
          set -x
          [[ "$(nix config show sandbox)" == '${{ github.event.inputs.sandbox }}' ]]

      - name: Build
        run: |
          if [[ '${{ github.event.inputs.force-rebuild }}' == 'true' ]]; then
            nix-build --attr 'pkgs.${{ matrix.pname }}' --option substitute false
          else
            nix-build --attr 'pkgs.${{ matrix.pname }}'
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          # Should trim `-` for path available if using inputs.repository
          name: 'build-${{ matrix.pname }}-${{ inputs.ref }}-${{ runner.arch }}-${{ runner.os }}'
          path: './result*'
          if-no-files-found: 'error'
          # This is a broken change in their minor version updates. See https://github.com/actions/upload-artifact/commit/cb6558bb10fe4afe4054d0be4b3136e673eb5e7f and https://github.com/actions/upload-artifact/pull/598
          include-hidden-files: 'true' # Required for `bin/.bin-wrapped`
